# Generated by Django 5.1.1 on 2024-10-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
