# Generated by Django 5.1.1 on 2024-10-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_parkingspot_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
