# Generated by Django 5.1.1 on 2024-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_bookinghistory_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='parking_spot_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
