# Generated by Django 5.1.1 on 2024-10-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_bookinghistory_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
