# Generated by Django 5.1.1 on 2024-10-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_booking_rotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rotation',
        ),
    ]
